'use client';
 
import { useChat } from 'ai/react';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f3RZmJbQjn4
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"

export function Qai() {
  const { messages, input, handleInputChange, handleSubmit } = useChat();
  return (
    <div className="grid w-full gap-4 lg:grid-cols-2 items-start bg-black p-4 rounded-lg">
      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-2">
          <Label className="text-lg font-medium text-white" htmlFor="query">
            Ask a question
          </Label>
          <div className="grid w-full gap-2 border border-gray-200 border-blue-300 rounded-lg p-2 bg-black dark:border-gray-800">
          <form onSubmit={handleSubmit}>  
          <input className="text-white bg-black" id="query" 
          value={input}
          placeholder="What is the capital of France?"
          onChange={handleInputChange}/>
          <Button
            className="w-full max-w-xs bg-black text-white rounded-lg shadow-neon-pink border-2 border-pink-500 animate-pulse"
            type="submit">
            Submit
          </Button>
          </form>
          </div>
        </div>
        <div className="flex flex-col gap-2">
  <Label className="text-lg font-medium text-white" htmlFor="answer">
    Answer
  </Label>
  <Textarea
    className="cursor-not-allowed bg-black text-white"
    id="answer"
    placeholder="Your answer will appear here once the AI has processed your question."
    readOnly
  />
  {messages.map(m => (
    <div key={m.id} className="whitespace-pre-wrap">
      {m.role === 'user' ? 'User: ' : 'AI: '}
      {m.content}
    </div>
  ))}
</div>
      </div>
    </div>
  )
}


 

  
 
      
        
    
}